spring.application.name=ss3_bai2

server.port=8081
# 1. Gemini (Cung c?p project-id gi? l?p ?? v??t qua b??c check kh?i t?o)
spring.ai.vertex.ai.gemini.project-id=mock-project-id
spring.ai.vertex.ai.gemini.location=us-central1

# 2. OpenAI (Cung c?p mock key và t?t các model không dùng t?i)
spring.ai.openai.api-key=mock-openai-key
spring.ai.openai.chat.enabled=true
spring.ai.openai.audio.speech.enabled=false
spring.ai.openai.audio.transcription.enabled=false
spring.ai.openai.image.enabled=false
spring.ai.openai.embedding.enabled=false

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model= qwen2.5:7b
spring.ai.ollama.chat.options.temperature=0.7